from dateutil.relativedelta import relativedelta as rd
from CommonDataServices import transform_utils as tu
from ConsumerServices.DatasetTools.DatasetDefs import gold_prices

agg_pipe_outputs={
    "Accounts":
    [
        {        
            "PipeName":"AccountCount",   
            "AsofDate":[
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "Facts":
            {
                "TotalAccounts":
                {
                    "OutputCol":"AccountCount",
                    "Dim":None,
                    "PostProcs":{"FormatNumber":"%d"},
                },
            }
        },
        {
            "PipeName":"AccountAggsPL",
            "AsofDate":[
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "Facts":
            {
                "TotalPrincOutstandingPL":
                {
                    "OutputCol":"TotalPrincOSPL",
                    "Dim":None,
                    "PostProcs":{
                        "FormatNumber":"%d"
                    },
                },
                "TotalCollWeightPL":
                {
                    "OutputCol":"TotalCollWeightPL",
                    "Dim":None,
                    "PostProcs":{
                        "FormatNumber":"%d"
                    }, 
                },
            },
        },
        {
            "PipeName":"AccountAggsExPL",
            "AsofDate":[
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "Facts":
            {
                "TotalPrincOutstandingExPL":
                {
                    "OutputCol":"TotalPrincOSExPL",
                    "Dim":None,
                    "PostProcs":{"FormatNumber":"%d"},
                },
                "TotalCollWeightExPL":
                {
                    "OutputCol":"TotalCollWeightExPL",
                    "Dim":None,
                    "PostProcs":{
                        "FormatNumber":"%d"
                    }, 
                },
            },
        },
        {
            "PipeName":"NewLoansCount1Q",
            "AsofDate":[
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "Facts":
            {
                "NewLoansCount1Q":
                {
                    "OutputCol":"AccountCount",
                    "Dim":None,
                    "PostProcs":{"FormatNumber":"%d"},
                },
            },
        },
        {
            "PipeName":"NewLoansSize1QPL",
            "AsofDate":[
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "Facts":
            {
                "NewLoansAvgPrinc1QPL":
                {
                    "OutputCol":"AvgLoanAmount",
                    "Dim":None,
                    "PostProcs":{"FormatNumber":"%d"},
                },
                "NewLoansCollWeight1Q":
                {
                    "OutputCol":"AvgWeight",
                    "Dim":None,
                    "PostProcs":{"FormatNumber":"%d"},
                },
                "NewLoansTotalLoanAmount1QPL":
                {
                    "OutputCol":"TotalLoanAmount",
                    "Dim":None,
                    "PostProcs":{"FormatNumber":"%d"},
                },
            },
        },
        {
            "PipeName":"NewLoansSize1QExPL",
            "AsofDate":[
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "Facts":
            {
                "NewLoansAvgPrinc1QExPL":
                {
                    "OutputCol":"AvgPrincRepaid",
                    "Dim":None,
                    "PostProcs":{"FormatNumber":"%d"},
                },
                "NewLoansTotalLoanAmount1QExPL":
                {
                    "OutputCol":"TotalPrincRepaid",
                    "Dim":None,
                    "PostProcs":{"FormatNumber":"%d"},
                },
            },
        },
        {
            "PipeName":"LoanClosuresCount1Q",
            "AsofDate":[
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "Facts":
            {
                "LoanClosuresCount1Q":
                {
                    "OutputCol":"AccountCount",
                    "Dim":None,
                    "PostProcs":{"FormatNumber":"%d"},
                },
            },
        },    
        {
            "PipeName":"LoanClosuresSize1Q",
            "AsofDate":[
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "Facts":
            {
                "LoanClosuresPrinc1Q":
                {
                    "OutputCol":"AvgLoanAmount",
                    "Dim":None,
                    "PostProcs":{"FormatNumber":"%d"},
                },
                "LoanClosuresCollWeight1Q":
                {
                    "OutputCol":"AvgWeight",
                    "Dim":None,
                    "PostProcs":{"FormatNumber":"%d"},
                },
            },
        },
        {
            "PipeName":"LTVLimitBreachesPL",
            "PipeParams":[
                {
                    "ParamType":"Fact",
                    "ParamName":"GoldPrice",
                    "ParamDef":{"SourceType":"RefData","Source":"GoldPrice","Params":"AsofDate"}
                },
                {
                    "ParamType":"PipeConstants",
                    "ParamName":"ConstantList",
                    "ParamDef":{"SourceType":"FactDef","Source":"Params","Params":{"LTVLimit":0.75}}
                }
            ],
            "AsofDate":[
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "Facts":
            {
                "TotalPrincOSPL_LTVBreaches":
                {
                    "OutputCol":"TotalPrincOS",
                    "Dim":None,
                    "PostProcs":{"FormatNumber":"%d"},
                },
                "AccountCountPL_LTVBreaches":
                {
                    "OutputCol":"AccountCount",
                    "Dim":None,
                    "PostProcs":{"FormatNumber":"%d"},
                },
            },
        },
        {
            "PipeName":"LTVLimitBreachesExPL",
            "PipeParams":[
                {
                    "ParamType":"Fact",
                    "ParamName":"GoldPrice",
                    "ParamDef":{"SourceType":"RefData","Source":"GoldPrice","Params":"AsofDate"}
                },
                {
                    "ParamType":"PipeConstants",
                    "ParamName":"ConstantList",
                    "ParamDef":{"SourceType":"FactDef","Source":"Params","Params":{"LTVLimit":0.75}}
                }
            ],
            "AsofDate":[
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "Facts":
            {
                "TotalPrincOSExPL_LTVBreaches":
                {
                    "OutputCol":"TotalPrincOS",
                    "Dim":None,
                    "PostProcs":{"FormatNumber":"%d"},
                },
                "AccountCountExPL_LTVBreaches":
                {
                    "OutputCol":"AccountCount",
                    "Dim":None,
                    "PostProcs":{"FormatNumber":"%d"},
                },
            },
        },
        {
            "PipeName":"LoansPastCloseDatePL",
            "AsofDate":[
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "Facts":
            {
                "TotalPrincOSPL_PastCls":
                {
                    "OutputCol":"TotalPrincOS",
                    "Dim":None,
                    "PostProcs":{"FormatNumber":"%d"},
                },
                "AccountCountPL_PastCls":
                {
                    "OutputCol":"AccountCount",
                    "Dim":None,
                    "PostProcs":{"FormatNumber":"%d"},
                },
            },
        },    
        {
            "PipeName":"LoansPastCloseDateExPL",
            "AsofDate":[
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "Facts":
            {
                "TotalPrincOSExPL_PastCls":
                {
                    "OutputCol":"TotalPrincOS",
                    "Dim":None,
                    "PostProcs":{"FormatNumber":"%d"},
                },
                "AccountCountExPL_PastCls":
                {
                    "OutputCol":"AccountCount",
                    "Dim":None,
                    "PostProcs":{"FormatNumber":"%d"},
                },
            },
        },
        {
            "PipeName":"LoansWithNotices",
            "AsofDate":[
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "Facts":
            {
                "TotalPrincOS_Notices":
                {
                    "OutputCol":"TotalPrincOS",
                    "Dim":None,
                    "PostProcs":{"FormatNumber":"%d"},
                },
                "AccountCount_Notices":
                {
                    "OutputCol":"AccountCount",
                    "Dim":None,
                    "PostProcs":{"FormatNumber":"%d"},
                },
            },
        },          
    ],
    "Transactions":
    [
        {
            "PipeName":"ReceiptsCount1Q",
            "AsofDate":[
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "Facts":
            {
                "ReceiptsCount1Q":
                {
                    "OutputCol":"ReceiptCount",
                    "Dim":None,
                    "PostProcs":{"FormatNumber":"%d"},
                },
            },
        },
        {
            "PipeName":"ReceiptsSize1Q",
            "AsofDate":[
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "Facts":
            {
                "IntRec1Q":
                {
                    "OutputCol":"TotalReceipts",
                    "Dim":"IntPayment",
                    "PostProcs":{"FormatNumber":"%d"},
                },
                "PrincRec1Q":
                {
                    "OutputCol":"TotalReceipts",
                    "Dim":"PrincPayment",
                    "PostProcs":{"FormatNumber":"%d"},
                },
            },
        },
    ]
}
ref_data_facts=[   
    {        
        "FactName":"GoldPrice",
        "Source":"GoldPrices",#Gold Prices dataset 
        "AsofDate":
        [
            {"RefDate":"ReportCOB","Delta":rd(days=0)},
            {"RefDate":"ReportCOB","Delta":rd(years=-1)},
            {"RefDate":"ReportCOB","Delta":rd(months=-3)}
        ],   
    } 
]
post_procs={
    "Facts_L1":
    [            
        {
            "FactName":"TotalPrincOutstanding",
            "CalcType":"SumFacts",
            "AsofDate":
            [
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "PageFactsList":[
                {
                    "SourceType":"AggPipeOutputs",
                    "Source":"Accounts",
                    "PipeName":"AccountAggsPL",
                    "PageDataItem":"TotalPrincOutstandingPL"
                },
                {
                    "SourceType":"AggPipeOutputs",
                    "Source":"Accounts",
                    "PipeName":"AccountAggsExPL",
                    "PageDataItem":"TotalPrincOutstandingExPL"
                },
            ],
        },
        {
            "FactName":"TotalCollWeight",
            "CalcType":"SumFacts",
            "AsofDate":
            [
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "PageFactsList":[
                {
                    "SourceType":"AggPipeOutputs",
                    "Source":"Accounts",
                    "PipeName":"AccountAggsPL",
                    "PageDataItem":"TotalCollWeightPL"
                },
                {
                    "SourceType":"AggPipeOutputs",
                    "Source":"Accounts",
                    "PipeName":"AccountAggsExPL",
                    "PageDataItem":"TotalCollWeightExPL"
                },
            ],
        },
        {            
            "FactName":"AvgReceiptCountPerDay1Q",
            "CalcType":"AvgOverTimeInterval",
            "AsofDate":
            [
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "Interval":rd(months=3),
            "DayCount":{"Type":"BD","Weekend":["Sun"]},
            "PageFactsList":
            [
                {
                    "SourceType":"AggPipeOutputs",
                    "Source":"Transactions",
                    "PipeName":"ReceiptsCount1Q",
                    "PageDataItem":"ReceiptsCount1Q",
                },
            ],
        },
        {            
            "FactName":"AvgNewLoansPerDay1Q",
            "CalcType":"AvgOverTimeInterval",
            "AsofDate":
            [
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "Interval":rd(months=3),
            "DayCount":{"Type":"BD","Weekend":["Sun"]},
            "PageFactsList":
            [
                {
                    "SourceType":"AggPipeOutputs",
                    "Source":"Accounts",
                    "PipeName":"NewLoansCount1Q",
                    "PageDataItem":"NewLoansCount1Q",
                },
            ],
        },
        {            
            "FactName":"NetCashOutflows1Q",
            "CalcType":"SumFacts",
            "AsofDate":
            [
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "PageFactsList":[
                {
                    "SourceType":"AggPipeOutputs",
                    "Source":"Transactions",
                    "PipeName":"ReceiptsSize1Q",
                    "PageDataItem":"IntRec1Q",
                    "Multiplier":-1
                },
                {
                    "SourceType":"AggPipeOutputs",
                    "Source":"Transactions",
                    "PipeName":"ReceiptsSize1Q",
                    "PageDataItem":"PrincRec1Q",
                    "Multiplier":-1
                },
                {
                    "SourceType":"AggPipeOutputs",
                    "Source":"Accounts",
                    "PipeName":"NewLoansSize1QPL",
                    "PageDataItem":"NewLoansTotalLoanAmount1QPL",
                },
                {
                    "SourceType":"AggPipeOutputs",
                    "Source":"Accounts",
                    "PipeName":"NewLoansSize1QExPL",
                    "PageDataItem":"NewLoansTotalLoanAmount1QExPL",
                }
            ],
        },
        {
            "FactName":"TotalPrincOutstanding_LTVBreaches",
            "CalcType":"SumFacts",
            "AsofDate":
            [
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "PageFactsList":[
                {
                    "SourceType":"AggPipeOutputs",
                    "Source":"Accounts",
                    "PipeName":"LTVLimitBreachesPL",
                    "PageDataItem":"TotalPrincOSPL_LTVBreaches"
                },
                {
                    "SourceType":"AggPipeOutputs",
                    "Source":"Accounts",
                    "PipeName":"LTVLimitBreachesExPL",
                    "PageDataItem":"TotalPrincOSExPL_LTVBreaches"
                },
            ],
        },
        {
            "FactName":"AccountCount_LTVBreaches",
            "CalcType":"SumFacts",
            "AsofDate":
            [
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "PageFactsList":[
                {
                    "SourceType":"AggPipeOutputs",
                    "Source":"Accounts",
                    "PipeName":"LTVLimitBreachesPL",
                    "PageDataItem":"AccountCountPL_LTVBreaches"
                },
                {
                    "SourceType":"AggPipeOutputs",
                    "Source":"Accounts",
                    "PipeName":"LTVLimitBreachesExPL",
                    "PageDataItem":"AccountCountExPL_LTVBreaches"
                },
            ],
        },
        {
            "FactName":"AccountCount_PastCls",
            "CalcType":"SumFacts",
            "AsofDate":
            [
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "PageFactsList":[
                {
                    "SourceType":"AggPipeOutputs",
                    "Source":"Accounts",
                    "PipeName":"LoansPastCloseDatePL",
                    "PageDataItem":"AccountCountPL_PastCls"
                },
                {
                    "SourceType":"AggPipeOutputs",
                    "Source":"Accounts",
                    "PipeName":"LoansPastCloseDateExPL",
                    "PageDataItem":"AccountCountExPL_PastCls"
                },
            ],
        },
        {
            "FactName":"TotalPrincOS_PastCls",
            "CalcType":"SumFacts",
            "AsofDate":
            [
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "PageFactsList":[
                {
                    "SourceType":"AggPipeOutputs",
                    "Source":"Accounts",
                    "PipeName":"LoansPastCloseDatePL",
                    "PageDataItem":"TotalPrincOSPL_PastCls"
                },
                {
                    "SourceType":"AggPipeOutputs",
                    "Source":"Accounts",
                    "PipeName":"LoansPastCloseDateExPL",
                    "PageDataItem":"TotalPrincOSExPL_PastCls"
                },
            ],
        },
    ],
    "Facts_L2":
    [
        {    
            "FactName":"PortfolioLTV",
            "CalcType":"FactArithmetic",
            "AsofDate":
            [
                {"RefDate":"ReportCOB","Delta":rd(days=0)},
                {"RefDate":"ReportCOB","Delta":rd(years=-1)},
                {"RefDate":"ReportCOB","Delta":rd(months=-3)}
            ],
            "Terms":
            [
                {    
                    "Op":"Div",
                    "Num":
                    {
                        "SourceType":"Facts",
                        "Level":"L1",
                        "PageDataItem":"TotalPrincOutstanding",
                    },
                    "Denom":
                    {
                        "SourceType":"Facts",
                        "Level":"L1",
                        "PageDataItem":"TotalCollWeight",
                        "Multiplier":{"SourceType":"RefData","Source":"GoldPrice","Params":"AsofDate"}
                    },
                },
            ],
        }
    ]
}


def get_fact(fact_def,filters={},dims={},fact_coll=None):
    if fact_def["SourceType"]=="RefData":
        if fact_def["Source"]=="GoldPrice":
            val= fact_coll["RefData"][filters["AsofDate"].strftime("%d-%b-%Y")]["GoldPrice"]
            msg=f"Gold Price fetched from home page data ref data store"
            status="Success"
    elif fact_def["SourceType"]=="FactDef":
        if fact_def["Source"]=="Params":
            try:
                val=fact_def["Params"]
                msg=f"Sourced fact from params attribute of {fact_def}"
                status="Success"
            except KeyError:
                val=None
                msg=f"{fact_def} does not have a Params attribute although Source and Source Type are defined as FactDef, Params"
                status="Failed"
    elif fact_def["SourceType"]=="Facts":
        #read from fact_coll, which is the page data dict from home_page.py
        try:
            mult_def=fact_def["Multiplier"]
            mult=get_fact(mult_def,filters,dims,fact_coll)["Value"]#recursive call to get multiplier
        except KeyError as e:
            mult=1.0
        if fact_def["Level"]=="L1":
            try:
                val= fact_coll["Facts_L1"][filters["AsofDate"].strftime("%d-%b-%Y")][fact_def["PageDataItem"]]*mult
                status="success"
                msg=f"{fact_def['PageDataItem']} for cob {filters['AsofDate'].strftime('%d-%b-%Y')} found in Level 1 of home page data facts"
            except KeyError:
                val=None
                status="Failed"
                msg=f"{fact_def['PageDataItem']} for cob {filters['AsofDate'].strftime('%d-%b-%Y')} not found in Level 1 of home page data facts"
        elif fact_def["Level"]=="L2":
            try:
                val= fact_coll["Facts_L2"][filters["AsofDate"].strftime("%d-%b-%Y")][fact_def["PageDataItem"]]*mult
                status="success"
                msg=f"{fact_def['PageDataItem']} for cob {filters['AsofDate'].strftime('%d-%b-%Y')} found in Level 2 of home page data facts"
            except KeyError:
                val=None
                status="Failed"
                msg=f"{fact_def['PageDataItem']} for cob {filters['AsofDate'].strftime('%d-%b-%Y')} not found in Level 2 of home page data facts"
    else:
        val=None
        status="Failed"
        msg=f"Fact not implemented for type {fact_def['SourceType']}"
    return {"Value":val,"Status":status,"Message":msg}