# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - PFSIntranet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          cd IntranetAzure
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          cd IntranetAzure
          source venv/bin/activate
          pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip IntranetAzure directory for deployment
        run: |
          cd IntranetAzure
          zip -r ../release.zip ./* -x "venv/*" "__pycache__/*" "*.pyc"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            web.config

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          # Extract to a temporary directory
          unzip release.zip -d temp_deployment
          # Move web.config to root if it exists
          if [ -f web.config ]; then
            mv web.config temp_deployment/
          fi

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'PFSIntranet'
          slot-name: 'Production'
          package: temp_deployment
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_49D666F3E3034BFF8E49F10F2788EBEA }}
